In [2]:
import pandas as pd

In [28]:
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
df = pd.DataFrame(data)
df['总分'] = df[['数学', '英语', '物理']].sum(axis=1)
df['平均分'] = df[['数学', '英语', '物理']].mean(axis=1)
print(df[(df.数学>90) | (df.英语>85)])
# df.sort_values(by='总分', ascending=False).head(3)
df.nlargest(3, '总分')

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

In [34]:
data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}
df = pd.DataFrame(data)
df['总销售额'] = df['单价'] * df['销量']
# df.nlargest(1, '总销售额')
df.sort_values(by='总销售额', ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000